# Generated by Django 2.1.7 on 2019-06-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190523_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Student', 'Student')], default='Mentor', max_length=20),
        ),
    ]
