# Generated by Django 2.1.7 on 2019-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190603_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Student', 'Student')], max_length=20),
        ),
    ]
