# Generated by Django 2.1.7 on 2019-03-29 12:47

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190329_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(blank=True, max_length=140, validators=[tweets.validators.validate_content]),
        ),
    ]
